# Base image
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy app source
COPY . .

# The port should match what Railway expects
ENV PORT=3001

# Expose port
EXPOSE 3001

# Start command
CMD ["node", "app.js"] 