apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkiapuri-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arkiapuri-api
  template:
    metadata:
      labels:
        app: arkiapuri-api
    spec:
      containers:
        - name: api
          image: your-registry/arkiapuri-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri
